<?php
	require_once('includes/header.php');
	include_once('includes/nav.php');
	include_once('includes/announcement.php');
	include_once('includes/slider.php');
	include_once('includes/info-section.php');
	include_once('includes/slider-promo-video-fbpage.php');
	include_once('includes/partner.php');
	require_once('includes/footer.php');
?>